# The release gate for POEMED: the check CRAN runs, run here first, in full.
#
# No tarball leaves this machine without a full-mode run of this script
# printing ALL GATES PASSED and writing its record (with the tarball's
# sha256) to the Quality Control folder. It is POEMED's copy of the portfolio
# release gate (Kelley_R_Package_QC_Master.md, "Release gate", decided
# 2026-08-21, after DMAR's CRAN returns proved that checks run with a step
# disabled let detectable defects through). Nothing here is optional and
# nothing is skipped for speed in full mode.
#
# Usage, from the package root:
#   caffeinate -i Rscript tools/release_gate.R            # full mode, before any tarball
#   Rscript tools/release_gate.R --quick                  # after any documentation edit
#
# Full mode refuses to start on macOS without a caffeinate assertion,
# because the timing gates read wall-clock times from the check and a
# machine that sleeps mid-run records minutes of elapsed time against
# seconds of CPU. Do not edit this file while a run is in progress: R
# reads it incrementally.
#
# Quick mode runs the static invariants (tools/release_checks.R),
# regenerates the Rd files and refuses stale documentation, renders the
# whole PDF manual through LaTeX, and runs the spelling and pkgdown gates.
# Every gate prints PASS, FAIL, or SKIP. A step that did not run (a check
# R CMD check itself skipped, or a static check whose input is absent from
# the tree) is recorded as SKIP with its reason, never as PASS; it does not
# fail the gate, and the final line and the record list it by name. Both
# modes also read the letter to CRAN (cran-comments.md) and report how many
# placeholders are still to be filled; that count never fails the gate,
# because the letter is completed after the win-builder runs.
# Full mode adds: a version and date that can be released, a clean working
# tree, the tarball built from the committed tree outside Dropbox,
# R CMD check --as-cran with both manuals and the remote URL checks, the
# example and whole-check time budgets, the complete local test suite
# (the article's pinned values included), the live oracle against the
# reference implementation that produced the article's numbers, and a
# sweep of the tarball and git history for anything that should not be in
# them. tools/ is excluded from the tarball by .Rbuildignore.

args  <- commandArgs(trailingOnly = TRUE)
quick <- "--quick" %in% args
root  <- normalizePath(".")
if (!file.exists(file.path(root, "DESCRIPTION"))) stop("Run from the package root.", call. = FALSE)
dest  <- sub("^--dest=", "", grep("^--dest=", args, value = TRUE))
if (!length(dest)) dest <- dirname(root)   # the R folder holds release tarballs
# The Quality Control folder sits beside the packages in the R folder.
qc_dir <- file.path(dirname(root), "Quality Control", basename(root))
dir.create(qc_dir, showWarnings = FALSE, recursive = TRUE)

pkg <- read.dcf("DESCRIPTION", fields = c("Package", "Version", "Date"))
tarball_name <- sprintf("%s_%s.tar.gz", pkg[, "Package"], pkg[, "Version"])

# The results live in a small environment, so no function here assigns
# outside its own frame.
state <- new.env(parent = emptyenv())
state$results <- list()
record_result <- function(name, status, detail) {
  cat(sprintf("[%s] %s\n", status, name))
  for (d in detail) cat("       ", d, "\n", sep = "")
  state$results[[length(state$results) + 1L]] <- list(name = name, status = status, detail = detail)
}
gate <- function(name, ok, detail = character()) {
  record_result(name, if (isTRUE(ok)) "PASS" else "FAIL", detail)
  invisible(isTRUE(ok))
}
# A step that did not run: recorded and listed as skipped, with the reason.
gate_skip <- function(name, reason) {
  record_result(name, "SKIP", reason)
  invisible(NA)
}
statuses <- function() vapply(state$results, `[[`, "", "status")
skipped_names <- function() vapply(Filter(function(r) r$status == "SKIP", state$results), `[[`, "", "name")
skip_summary <- function() {
  sk <- skipped_names()
  if (!length(sk)) "none skipped" else sprintf("%d skipped [%s]", length(sk), paste(sk, collapse = "; "))
}
run <- function(cmd, args, log) {
  status <- system2(cmd, args, stdout = log, stderr = log)
  list(status = status, lines = readLines(log, warn = FALSE))
}
# A git that actually runs (see tools/release_checks.R: /usr/local/bin/git
# here is a stale Intel binary that exits 126 and would make every git gate
# pass on empty output).
git_bin <- local({
  cands <- unique(c(Sys.which("git"), "/usr/bin/git", "/opt/homebrew/bin/git"))
  cands <- cands[nzchar(cands) & file.exists(cands)]
  ok <- vapply(cands, function(g) identical(suppressWarnings(
    tryCatch(system2(g, "--version", stdout = FALSE, stderr = FALSE), error = function(e) 1L)), 0L), logical(1))
  if (any(ok)) cands[ok][1] else NA_character_
})
git <- function(...) suppressWarnings(system2(git_bin, c(...), stdout = TRUE, stderr = FALSE))
work <- file.path(tempdir(), "release_gate")   # outside Dropbox, per the Release Protocol
dir.create(work, showWarnings = FALSE, recursive = TRUE)
t0 <- Sys.time()

## ---- Budgets ----------------------------------------------------------------
# POEMED has no accepted CRAN release yet, so the budgets are the portfolio's
# farm-derived lines rather than a measured acceptance: CRAN flags an
# example page over 5 s on its farm, and the slowest farm flavor has run
# portfolio examples at about three times the local elapsed time, so the
# local ceiling is 1.7 s per page; the incoming pretest's overall line is
# 10 minutes, so the whole local check is held to a third of it. After
# acceptance, replace this block with the measured release and its farm
# times (tools/cran_status.R in DMAR is the model).
page_ceiling_s <- 1.7
check_budget_s <- 200

## ---- 1. Static invariants ------------------------------------------------------
inv_log <- file.path(work, "release_checks.log")
inv <- run("Rscript", "tools/release_checks.R", inv_log)
inv_detail <- character()
if (inv$status != 0L) {
  keep <- FALSE
  for (l in inv$lines) {
    if (grepl("^\\[FAIL\\]", l)) { keep <- TRUE; inv_detail <- c(inv_detail, l); next }
    if (grepl("^\\[(PASS|SKIP)\\]", l)) { keep <- FALSE; next }
    if (keep && nzchar(trimws(l))) inv_detail <- c(inv_detail, trimws(l))
  }
}
gate("static invariants (tools/release_checks.R)", inv$status == 0L, inv_detail)
# A static check that could not run is listed here as a skipped gate, with
# the reason release_checks.R gave on the lines beneath it.
for (k in grep("^\\[SKIP\\] ", inv$lines)) {
  reason <- character()
  j <- k + 1L
  while (j <= length(inv$lines) && grepl("^\\s", inv$lines[j]) && !grepl("^\\s*building", inv$lines[j])) {
    reason <- c(reason, trimws(inv$lines[j])); j <- j + 1L
  }
  gate_skip(paste("static:", sub("^\\[SKIP\\] ", "", inv$lines[k])), reason)
}

## ---- 2. Rd markup inside math (parsed, not grepped) --------------------------------
math_markup <- "\\\\(code|emph|link|strong|pkg|bold|var|samp|file|env|dQuote|sQuote|href|url)\\{"
math_nodes <- function(x) {
  tag <- attr(x, "Rd_tag")
  here <- if (!is.null(tag) && tag %in% c("\\eqn", "\\deqn")) paste(unlist(x), collapse = "") else character()
  below <- if (is.list(x)) unlist(lapply(x, math_nodes)) else character()
  c(here, below)
}
rd_db <- tools::Rd_db(dir = ".")
hits <- names(Filter(function(rd) any(grepl(math_markup, math_nodes(rd))), rd_db))
gate("no Rd markup inside \\eqn{} or \\deqn{} (parsed, all pages)", length(hits) == 0L, hits)

## ---- 3. Documentation current --------------------------------------------------
doc_files <- c(list.files("man", pattern = "[.]Rd$", full.names = TRUE), "NAMESPACE")
before <- tools::md5sum(doc_files)
suppressMessages(roxygen2::roxygenise(roclets = c("rd", "namespace")))
doc_files <- c(list.files("man", pattern = "[.]Rd$", full.names = TRUE), "NAMESPACE")
after <- tools::md5sum(doc_files)
stale <- c(setdiff(names(after), names(before)), setdiff(names(before), names(after)),
           names(before)[names(before) %in% names(after) & before != after[names(before)]])
gate("documentation current (roxygen regenerates nothing)", length(stale) == 0L, stale)

## ---- 4. The PDF manual renders through LaTeX --------------------------------------
pdf_log <- file.path(work, "Rd2pdf.log")
pdf_out <- file.path(work, "manual.pdf")
unlink(pdf_out)
pdf <- run("R", c("CMD", "Rd2pdf", "--no-preview", "--force",
                  paste0("--output=", pdf_out), "."), pdf_log)
latex_err <- grep("^! |LaTeX errors|Missing \\$ inserted", pdf$lines, value = TRUE)
gate("PDF manual renders (R CMD Rd2pdf, full LaTeX pass)",
     pdf$status == 0L && file.exists(pdf_out) && length(latex_err) == 0L,
     c(if (pdf$status != 0L) sprintf("Rd2pdf exit status %d", pdf$status), head(latex_err, 10)))

## ---- 5. Spelling and pkgdown ---------------------------------------------------
sp <- spelling::spell_check_package(".")
gate("spelling (inst/WORDLIST)", nrow(sp) == 0L,
     if (nrow(sp)) sprintf("%s: %s", sp$word, vapply(sp$found, paste, "", collapse = ", ")))
pk <- tryCatch({ pkgdown::check_pkgdown("."); TRUE }, error = function(e) conditionMessage(e))
gate("pkgdown reference index complete", isTRUE(pk), if (!isTRUE(pk)) pk)

## ---- 5a. The letter to CRAN: placeholders still to be filled -------------------------
# cran-comments.md is completed after the win-builder runs, so an unfilled
# placeholder never fails the gate; the count, and the lines that carry
# one, go in the final line and the record so that no letter leaves with
# one. The marker is assembled here rather than written out, so a search of
# the repository for it finds the letter alone. The counter is shown a
# known-bad line first and must count it.
fill_marker <- paste0(strrep("[", 2L), "FILL")
count_fill <- function(lines) sum(lengths(regmatches(lines, gregexpr(fill_marker, lines, fixed = TRUE))))
fill_control <- identical(count_fill(sprintf("a %s: x]] b %s: y]]", fill_marker, fill_marker)), 2L) &&
  identical(count_fill("a filled line"), 0L)
gate("letter placeholder counter flags its known-bad case", fill_control)
letter <- if (file.exists("cran-comments.md")) readLines("cran-comments.md", warn = FALSE) else NULL
letter_fill <- if (is.null(letter)) NA_integer_ else count_fill(letter)
letter_lines <- if (is.null(letter)) integer() else grep(fill_marker, letter, fixed = TRUE)
letter_summary <- if (is.null(letter)) {
  "letter to CRAN: cran-comments.md not found"
} else if (letter_fill == 0L) {
  "letter to CRAN: no unfilled placeholders"
} else {
  sprintf("letter to CRAN: %d unfilled %s]] placeholder%s (cran-comments.md line%s %s)", letter_fill,
          fill_marker, if (letter_fill == 1L) "" else "s", if (length(letter_lines) == 1L) "" else "s",
          paste(letter_lines, collapse = ", "))
}
cat("        ", letter_summary, "\n", sep = "")

if (quick) {
  ok_all <- !any(statuses() == "FAIL")
  cat(sprintf("\nquick mode: %d gates, %d failed, %s; %s; %.0f s\n", length(state$results),
              sum(statuses() == "FAIL"), skip_summary(), letter_summary,
              as.numeric(difftime(Sys.time(), t0, units = "secs"))))
  if (!ok_all) quit(status = 1L)
  cat("QUICK GATES PASSED (not a release: run full mode before any tarball leaves)\n")
  quit(status = 0L)
}

## ---- 6. Awake, a working git, and a version and date that can be released --------
if (Sys.info()[["sysname"]] == "Darwin") {
  assertions <- tryCatch(system2("pmset", c("-g", "assertions"), stdout = TRUE), error = function(e) character())
  awake <- any(grepl("caffeinate", assertions, fixed = TRUE, useBytes = TRUE))
  gate("machine kept awake for the timing gates (caffeinate assertion present)", awake,
       if (!awake) "start with: caffeinate -i Rscript tools/release_gate.R")
  if (!awake) { cat("\nGATE FAILED before the check ran; nothing recorded\n"); quit(status = 1L) }
}
gate(sprintf("a working git is available (%s)", git_bin), !is.na(git_bin),
     if (is.na(git_bin)) "no git binary ran; checked Sys.which, /usr/bin, /opt/homebrew/bin")
if (is.na(git_bin)) { cat("\nGATE FAILED: git is required to certify a commit\n"); quit(status = 1L) }

cran_ver <- tryCatch({
  ap <- utils::available.packages(repos = "https://cloud.r-project.org")
  if (pkg[, "Package"] %in% rownames(ap)) unname(ap[pkg[, "Package"], "Version"]) else "none"
}, error = function(e) NA_character_)
this_ver <- unname(pkg[, "Version"])
ver_ok <- !is.na(cran_ver) &&
  (identical(cran_ver, "none") || package_version(this_ver) > package_version(cran_ver))
gate(sprintf("version %s can be released (on CRAN: %s)", this_ver,
             if (is.na(cran_ver)) "lookup failed" else if (cran_ver == "none") "not yet, new submission" else cran_ver),
     ver_ok,
     if (is.na(cran_ver)) "CRAN could not be reached (the URL checks need the network too)"
     else if (!ver_ok) "bump Version in DESCRIPTION and open its NEWS heading before certifying")
desc_date <- tryCatch(as.Date(unname(pkg[, "Date"])), error = function(e) as.Date(NA))
date_age <- as.numeric(Sys.Date() - desc_date)
gate(sprintf("DESCRIPTION Date %s is the certification day (within three days)", format(desc_date)),
     !is.na(date_age) && date_age >= 0 && date_age <= 3,
     if (is.na(date_age)) "DESCRIPTION has no parseable Date field"
     else if (date_age < 0 || date_age > 3) "date the release the day it is certified; CRAN notes a Date over a month old")

## ---- 7. Clean tree; the tarball is the committed tree -------------------------------
dirty <- git("status", "--porcelain")
gate("working tree clean (the gate certifies a commit, not a draft)",
     length(dirty) == 0L && is.null(attr(dirty, "status")), dirty)
sha <- git("rev-parse", "--short", "HEAD")
src <- file.path(work, "src"); unlink(src, recursive = TRUE); dir.create(file.path(src, pkg[, "Package"]), recursive = TRUE)
system(sprintf("%s archive HEAD | tar -x -C %s", shQuote(git_bin), shQuote(file.path(src, pkg[, "Package"]))))
old <- setwd(src)
bld <- run("R", c("CMD", "build", pkg[, "Package"]), file.path(work, "build.log"))
setwd(old)
tarball <- file.path(src, tarball_name)
gate(sprintf("tarball built from commit %s (git archive, outside Dropbox)", sha),
     bld$status == 0L && file.exists(tarball), if (bld$status != 0L) tail(bld$lines, 5))

## ---- 8. R CMD check --as-cran, manuals on, remote URL checks on ------------------
chk_log <- file.path(work, "check.log")
old <- setwd(src)
Sys.setenv(`_R_CHECK_CRAN_INCOMING_REMOTE_` = "true", `_R_CHECK_FORCE_SUGGESTS_` = "true",
           `_R_CHECK_TIMINGS_` = "0")
chk_t0 <- Sys.time()
chk <- run("R", c("CMD", "check", "--as-cran", tarball_name), chk_log)
chk_wall_s <- as.numeric(difftime(Sys.time(), chk_t0, units = "secs"))
setwd(old)
log <- chk$lines
status_line <- grep("^Status:", log, value = TRUE)
note_heads <- grep("\\.\\.\\. .*NOTE$", log, value = TRUE)
allowed_note <- function(h) grepl("CRAN incoming feasibility", h) ||
  (grepl("HTML version of manual", h) && any(grepl("recent enough HTML Tidy", log)))
bad_notes <- note_heads[!vapply(note_heads, allowed_note, logical(1))]
# The feasibility block may say only what a new submission says: "New
# submission". Anything else in it fails the gate, and no ERROR of any
# kind is allowed (the standard's Section 5.3, rule 4).
fi <- grep("CRAN incoming feasibility", log)[1]
feas <- if (is.na(fi)) character() else {
  k <- fi + 1L; out <- character()
  while (k <= length(log) && !grepl("^\\* ", log[k])) { out <- c(out, log[k]); k <- k + 1L }
  out
}
feas_extra <- grep("invalid file URIs|Non-FOSS|Insufficient package version|Size of tarball|Days since last update|misspelled|Found the following|invalid URLs|The Title field|The Description field|Conflicting package names",
                   feas, value = TRUE)
# URL problems: take the whole block, re-probe any 5xx (a gateway timeout at
# the checker's moment is environmental); only a reproducible problem fails,
# and every flagged URL is recorded either way.
url_start <- grep("invalid URLs", log)
url_bad <- character()
if (length(url_start)) {
  k <- url_start[1] + 1L; url_block <- character()
  while (k <= length(log) && grepl("^\\s", log[k])) { url_block <- c(url_block, trimws(log[k])); k <- k + 1L }
  urls <- sub("^URL: ", "", grep("^URL: ", url_block, value = TRUE))
  statuses <- sub("^Status: ", "", grep("^Status: ", url_block, value = TRUE))
  for (i in seq_along(urls)) {
    st <- if (i <= length(statuses)) statuses[i] else "?"
    u <- sub(" \\(moved to .*\\)$", "", urls[i])
    if (grepl("^5", st)) {
      code <- tryCatch(system2("curl", c("-s", "-o", "/dev/null", "-w", "%{http_code}", "-L", "--max-time", "20", shQuote(u)), stdout = TRUE), error = function(e) "000")
      if (identical(code, "200")) { cat("        transient ", st, " at check time; re-probe returned 200: ", u, "\n", sep = ""); next }
    }
    url_bad <- c(url_bad, sprintf("%s [%s]", urls[i], st))
  }
}
err_heads <- grep("ERROR$", log, value = TRUE)
warn_heads <- grep("WARNING$", log, value = TRUE)
gate("R CMD check --as-cran (manuals built): no ERROR and no WARNING",
     length(warn_heads) == 0L && length(err_heads) == 0L,
     c(status_line, warn_heads, err_heads))
gate("R CMD check: no NOTE beyond new submission",
     length(bad_notes) == 0L && length(feas_extra) == 0L && length(url_bad) == 0L,
     c(bad_notes, feas_extra,
       if (length(url_bad)) c("reproducible URL problems (the GitHub repository and its Pages site must be live):", url_bad)))
gate("PDF manual built by check", any(grepl("checking PDF version of manual \\.\\.\\..*OK", log)),
     grep("PDF version of manual", log, value = TRUE))
# The HTML manual. R CMD check skips its math rendering without the V8
# package and its validation without a recent HTML Tidy, and says so in the
# log; each such step is recorded as skipped, never as passed. A log with no
# HTML manual step at all fails, because then nothing was checked.
html_step <- grep("checking HTML version of manual", log, value = TRUE)
math_skip <- grep("Skipping checking math rendering", log, value = TRUE)
if (!length(html_step)) {
  gate("HTML manual checked by R CMD check", FALSE, "the check log has no HTML manual step")
} else if (length(math_skip)) {
  gate_skip("HTML manual: math rendering", c(trimws(math_skip), "install V8 so the check renders the formulas"))
} else {
  gate("HTML manual: no math rendering problems", !any(grepl("math rendering problems", log)),
       grep("math rendering", log, value = TRUE))
}
tidy_skip <- grep("Skipping checking HTML validation", log, value = TRUE)
if (length(tidy_skip))
  gate_skip("HTML manual: validation by HTML Tidy", c(trimws(tidy_skip), "win-builder validates it"))
timings <- grep("\\[[0-9]+s/[0-9]+s\\]", log, value = TRUE)
for (t in grep("checking (examples|re-building of vignette outputs|PDF version)|Running .testthat", timings, value = TRUE))
  cat("        ", t, "\n", sep = "")

## ---- 8a. Example and whole-check time budgets ---------------------------------------
ex_timings <- file.path(src, paste0(pkg[, "Package"], ".Rcheck"), paste0(pkg[, "Package"], "-Ex.timings"))
if (file.exists(ex_timings)) {
  et <- utils::read.table(ex_timings, header = TRUE)
  et$max <- pmax(et$user + et$system, et$elapsed)
  et <- et[order(-et$max), ]
  over <- et[et$max > page_ceiling_s, ]
  near <- et[et$max > 1.0 & et$max <= page_ceiling_s, ]
  gate(sprintf("no example page over %.1f s locally (slowest %.2f s: %s; %d pages, %.0f s in all)",
               page_ceiling_s, et$max[1], et$name[1], nrow(et), sum(et$elapsed)),
       nrow(over) == 0L,
       c(sprintf("%s %.2f s", over$name, over$max),
         if (nrow(near)) c("pages over 1 s:", sprintf("%s %.2f s", near$name, near$max))))
  cpu_ex <- sum(et$user + et$system); el_ex <- sum(et$elapsed)
  gate(sprintf("examples ran awake and unshared (%.0f s elapsed against %.0f s CPU)", el_ex, cpu_ex),
       el_ex <= 1.5 * cpu_ex + 5,
       if (el_ex > 1.5 * cpu_ex + 5) "elapsed far above CPU: the machine slept or was busy; rerun the gate")
} else {
  gate("example timings file present after the check", FALSE, ex_timings)
}
# A second example pass means an example block of the kind the master
# retires came back (one such block runs the whole corpus twice). The flag
# and the block's name are assembled from character codes.
dt_word <- intToUtf8(c(100, 111, 110, 116, 116, 101, 115, 116))
dt_pass <- sprintf("checking examples with %srun-%s", strrep("-", 2L), dt_word)
gate(sprintf("no second example pass (zero \\%s{} blocks)", dt_word),
     !any(grepl(dt_pass, log, fixed = TRUE)), grep(dt_pass, log, value = TRUE, fixed = TRUE))
step_secs <- function(pattern) {
  l <- grep(pattern, timings, value = TRUE)[1]
  if (is.na(l)) return(NA_real_)
  as.numeric(strsplit(gsub("[][s]", "", regmatches(l, regexpr("\\[[0-9]+s/[0-9]+s\\]", l))), "/")[[1]])[2]
}
feas_s <- step_secs("CRAN incoming feasibility")
check_total_s <- chk_wall_s - (if (is.na(feas_s)) 0 else feas_s)
gate(sprintf("whole check %.0f s locally (feasibility step excluded), within the %d s budget",
             check_total_s, check_budget_s),
     check_total_s <= check_budget_s,
     sprintf("%-40s", grep("checking (examples|re-building of vignette outputs|PDF version)|Running .testthat", timings, value = TRUE)))

## ---- 9. The full local test suite (NOT_CRAN, the article's pinned values) --------------
Sys.setenv(NOT_CRAN = "true")
tst <- tryCatch(as.data.frame(testthat::test_local(".", reporter = "silent", stop_on_failure = FALSE)),
                error = function(e) NULL)
tst_ok <- !is.null(tst) && sum(tst$failed) == 0L && sum(tst$error) == 0L && sum(tst$warning) == 0L
gate(sprintf("full local test suite: %s passed, %s failed, %s errors, %s warnings, %s skipped",
             if (is.null(tst)) "?" else sum(tst$passed), if (is.null(tst)) "?" else sum(tst$failed),
             if (is.null(tst)) "?" else sum(tst$error), if (is.null(tst)) "?" else sum(tst$warning),
             if (is.null(tst)) "?" else sum(tst$skipped)), tst_ok)

## ---- 10. Oracle: the reference implementation, against the tarball just checked ------------
# The harness calls POEMED:: by name, so it must see this tarball, not
# whatever version is installed in the user library.
gate_lib <- file.path(work, "lib"); unlink(gate_lib, recursive = TRUE); dir.create(gate_lib)
inst <- run("R", c("CMD", "INSTALL", "--no-docs", "--no-multiarch", paste0("--library=", gate_lib), tarball),
            file.path(work, "install.log"))
gate("tarball installs into a scratch library for the oracle run", inst$status == 0L,
     if (inst$status != 0L) tail(inst$lines, 8))
orc_log <- file.path(work, "oracle.log")
old_libs <- Sys.getenv("R_LIBS")
Sys.setenv(R_LIBS = paste(c(gate_lib, .libPaths()), collapse = .Platform$path.sep))
orc <- run("Rscript", "tools/oracle_checks.R", orc_log)
Sys.setenv(R_LIBS = old_libs)
orc_line <- grep("oracle checks:", orc$lines, value = TRUE)
gate("oracle harness (live comparison with the reference PEmediation implementation)",
     orc$status == 0L && length(orc_line) == 1L && !grepl(" [1-9][0-9]* skipped", orc_line),
     c(grep("^==|oracle checks:|^Error", orc$lines, value = TRUE),
       if (length(orc_line) && grepl(" [1-9][0-9]* skipped", orc_line)) "a skipped oracle is not a pass at release time"))

## ---- 11. Nothing in the tarball or the history that should not be ------------------
# The authorship residue and the conventions file's name are assembled from
# character codes, so this file never carries the strings it sweeps for.
# The sweep covers every ref that can reach GitHub. A local branch named
# *-private (the pre-release development history kept after the public
# branch was rebuilt as a single parentless commit, the route SIEVER and
# DMAR took) is excluded, and only while it has no upstream: the moment
# such a branch is tracked remotely it is back in the sweep.
refs <- git("for-each-ref", shQuote("--format=%(refname)"), "refs/heads", "refs/remotes", "refs/tags")
private_refs <- grep("^refs/heads/.*-private$", refs, value = TRUE)
tracked_private <- private_refs[vapply(private_refs, function(b)
  length(git("rev-parse", "--abbrev-ref", paste0(sub("^refs/heads/", "", b), "@{upstream}"))) > 0L, logical(1))]
# The gh-pages branch holds the built pkgdown site, written by the deploy
# action under the GitHub login (author "yelleKneK"); it is a generated
# artifact of the package, not its history, so it is not swept.
site_refs <- grep("(^|/)gh-pages$", refs, value = TRUE)
sweep_refs <- setdiff(refs, c(setdiff(private_refs, tracked_private), site_refs))
if (length(private_refs)) cat("        local-only, never pushed, excluded from the sweeps: ",
                              paste(sub("^refs/heads/", "", setdiff(private_refs, tracked_private)), collapse = ", "), "\n", sep = "")
if (length(site_refs)) cat("        generated site branch, excluded from the sweeps: ",
                           paste(site_refs, collapse = ", "), "\n", sep = "")
if (length(tracked_private)) cat("        WARNING: private branch has an upstream and is swept: ",
                                 paste(tracked_private, collapse = ", "), "\n", sep = "")
banned <- paste(c(intToUtf8(c(99,108,97,117,100,101)), intToUtf8(c(97,110,116,104,114,111,112,105,99)),
                  intToUtf8(c(99,111,45,97,117,116,104,111,114,101,100))), collapse = "|")
names_hit <- suppressWarnings(system(sprintf("tar -tzf %s | grep -icE '%s'", shQuote(tarball), banned), intern = TRUE))
content_hit <- suppressWarnings(system(sprintf("tar -xzOf %s 2>/dev/null | grep -icE '%s'", shQuote(tarball), banned), intern = TRUE))
log_hit <- suppressWarnings(system(sprintf("%s log %s --format=%%B | grep -icE '%s'", shQuote(git_bin), paste(shQuote(sweep_refs), collapse = " "), banned), intern = TRUE))
# grep -c exits 1 on a zero count, and system(intern = TRUE) then tags the
# "0" with a status attribute; compare the numbers, not the objects.
counts <- suppressWarnings(as.integer(c(names_hit, content_hit, log_hit)))
gate("tarball and git history carry no authorship residue",
     length(counts) == 3L && !anyNA(counts) && sum(counts) == 0L,
     sprintf("file names %s, file content %s, commit messages %s", names_hit, content_hit, log_hit))
# The Publication and Privacy Discipline: a private file that ever existed in
# a pushed history is public, whether or not it exists at HEAD.
ever <- unique(git("log", sweep_refs, "--name-only", "--pretty=format:"))
conv_file <- intToUtf8(c(67, 76, 65, 85, 68, 69, 46, 109, 100))   # the untracked conventions file, never named literally here
private_ever <- grep(paste0("(^|/)", conv_file, "$|[.]docx$|GAP-ANALYSIS|HANDOFF|RELEASE_QC|_QC_|audit|evaluation|decision|notes/"),
                     ever[nzchar(ever)], value = TRUE, ignore.case = TRUE)
gate("git history (every ref that can be pushed) never tracked a private working file", length(private_ever) == 0L,
     c(private_ever, if (length(private_ever)) "rewrite before any push (QC master, Publication and Privacy Discipline)"))
authors <- unique(git("log", sweep_refs, shQuote("--format=%an <%ae>")))
gate("every commit authored by the maintainer (Ken Kelley <kkelley@nd.edu>)",
     identical(authors, "Ken Kelley <kkelley@nd.edu>"), setdiff(authors, "Ken Kelley <kkelley@nd.edu>"))
std <- c("DESCRIPTION", "NAMESPACE", "NEWS.md", "README.md", "R", "build", "data", "inst", "man",
         "tests", "vignettes", "LICENSE", "LICENSE.md", "LICENSE.note")
surfaces <- unique(sub("/.*", "", sub("^[^/]+/", "", system(sprintf("tar -tzf %s", shQuote(tarball)), intern = TRUE))))
gate("tarball holds only the standard surfaces", all(surfaces %in% std), setdiff(surfaces, std))

## ---- Record and hand-off -------------------------------------------------------------
ok_all <- !any(statuses() == "FAIL")
n_fail <- sum(statuses() == "FAIL")
sha256 <- if (file.exists(tarball)) unname(tools::sha256sum(tarball)) else NA_character_
elapsed <- as.numeric(difftime(Sys.time(), t0, units = "mins"))
stamp <- format(Sys.time(), "%Y-%m-%d_%H%M")
record <- c(
  sprintf("# %s release gate, %s, commit %s", pkg[, "Package"], format(Sys.time(), "%Y-%m-%d %H:%M"), sha),
  "", sprintf("Result: %s (%d gates: %d passed, %d failed, %s; %.1f minutes)",
              if (ok_all) "ALL GATES PASSED" else "FAILED", length(state$results),
              sum(statuses() == "PASS"), n_fail, skip_summary(), elapsed),
  "", paste0("Letter: ", sub("^letter to CRAN: ", "", letter_summary)), "",
  sprintf("Tarball: %s", tarball_name), sprintf("sha256: %s", sha256), "",
  unlist(lapply(state$results, function(r) c(sprintf("- [%s] %s", r$status, r$name),
                                             if (length(r$detail)) paste0("    ", r$detail)))),
  "", "Check timings:", paste0("    ", timings), "",
  paste0("Check status: ", status_line))
rec_path <- file.path(qc_dir, sprintf("%s_release_gate_%s_%s.md", pkg[, "Package"], stamp, sha))
writeLines(record, rec_path)
cat(sprintf("\nrecord: %s\n", rec_path))
if (ok_all) {
  file.copy(tarball, file.path(dest, tarball_name), overwrite = TRUE)
  cat(sprintf("tarball: %s\nsha256:  %s\n", file.path(dest, tarball_name), sha256))
  cat(sprintf("\nALL GATES PASSED (%d gates, %s; %s; %.1f min)\n", length(state$results),
              skip_summary(), letter_summary, elapsed))
  cat("next: (1) R CMD INSTALL the certified tarball so the console matches the\n",
      "submission; (2) a win-builder r-devel run closes the HTML Tidy gap this\n",
      "machine cannot check; (3) upload exactly the file above and verify its\n",
      "sha256 against this record first.\n", sep = "")
  quit(status = 0L)
}
cat(sprintf("\nGATE FAILED: %d of %d gates failed (%s; %s); no tarball handed off\n",
            n_fail, length(state$results), skip_summary(), letter_summary))
quit(status = 1L)
